######################################################################
# Automatically generated by qmake (2.01a) Sat May 11 15:03:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += game.h pieces.h
SOURCES += main.cpp pieces.cpp
RESOURCES += pieces.qrc

OTHER_FILES += \
    chess pics/20130512060738772_easyicon_net_64.png
