######################################################################
# Automatically generated by qmake (2.01a) Fri May 3 00:23:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h game.h \
    wid1.h \
    wid2.h
SOURCES += board1.cpp game.cpp main.cpp \
    wid1.cpp \
    wid2.cpp

OTHER_FILES += \
    chess pics/Chess-Queen-icon.png \
    chess pics/help.png \
    chess pics/clear.png \
    chess pics/bg1.jpg \
    chess pics/bg2.jpg \
    ../easy.txt

FORMS += \
    wid1.ui \
    wid2.ui

RESOURCES += \
    Queen.qrc

contains(MEEGO_EDITION,harmattan) {
    target.path = /opt/test/bin
    INSTALLS += target
}
